builds:
- id: "secretary-lab"
  dir: ./cmd/secretary-lab/
  binary: secreatary-lab
  ldflags:
  -X github.com/chez-shanpu/secretary/cmd/secretary-lab/app.Version={{.Version}} -X github.com/chez-shanpu/secretary/cmd/secretary-lab/app.Revision={{.ShortCommit}}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm
  - arm64
