version: '3'

services:
  secretary-lab:
    image: ghcr.io/chez-shanpu/secretary-lab:latest
    #    build:
    #      dockerfile: ./docker/secretary-lab/Dockerfile
    #      context: .
    environment:
      LAB_DB_USER: sample
      LAB_DB_PASSWORD: sample
      LAB_DB_PROTOCOL: tcp 
      LAB_DB_ADDR: mysql 
      LAB_DB_NAME: secretary
      LAB_SLACK_TOKEN: sample
      LAB_SLACK_COMING_CHANNEL: sample
      GIN_MODE: release
    volumes:
    - ./config.yaml:/config.yaml
    entrypoint: [ "/secretary-lab" ]
    command: [ "run", "-p", "./config.yaml" ]
    ports:
    - "8080:8080"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - mysql:/var/lib/mysql
    - ./db/:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"

volumes:
  mysql:
