version: '3'

services:
  secretary-lab:
    image: ghcr.io/chez-shanpu/secretary-lab:stable
    environment:
      LAB_DB_USER: sample
      LAB_DB_PASSWORD: sample
      LAB_DB_NAME: sample
      LAB_SLACK_TOKEN: sample
      LAB_SLACK_COMING_CHANNEL: sample
    ports:
    - "8080:8080"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - mysql:/var/lib/mysql
    - ./db/:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"

volumes:
  mysql:
